module.exports = {
    deleteAddressUser: require('./deleteAddressUser'),
    deleteImageProducts: require('./deleteImageProduct'),
    deleteProduct: require('./deleteProduct'),
    getAddressByUser: require('./getAddressByUser'),
    getAllReviewDB: require('./getAllReviewDB'),
    getImageByProduct: require('./getImageByProduct'),
    getOrderByUser: require('./getOrderByUser'),
    getOrderStatus: require('./getOrderStatus'),
    getOrdersUsers: require('./getOrdersUsers'),
    getProductById: require('./getProductById'),
    getProductsDb: require('./getProductsDb'),
    getUserIdOrders: require('./getUserIdOrders'),
    getUsers: require('./getUsers'),
    packOffOrder: require('./packOffOrder'),
    updateAddressUser: require('./updateAddressUser'),
    updateProduct: require('./updateProduct'),
    updateUser: require('./updateUser'),
    uploadImage: require('./uploadImage'),
};